getwd()
pisaTrain = read.csv("pisa2009train.csv")
pisaTest = read.csv("pisa2009test.csv")
str(pisaTrain)
tapply(pisaTrain$readingScore,pisaTrain$male,mean,na.rm=TRUE )
summary(pisaTrain)
pisaTrain = na.omit(pisaTrain)
pisaTest = na.omit(pisaTest)
pisaTrain$raceeth = relevel(pisaTrain$raceeth, "White")
pisaTest$raceeth = relevel(pisaTest$raceeth, "White")
lmScore = lm (readingScore ~ .,data=pisaTrain)
summary(lmScore)
SSE = sum(lmScore$residuals^2)
RMSE = sqrt(SSE/nrow(pisaTrain))
predTest = predict(lmScore , newdata = pisaTest)
summary(predTest)
SSE = sum((predTest - pisaTest$readingScore)^2)
RMSE = sqrt(SSE/nrow(pisaTest))
baseline = mean(pisaTrain$readingScore)
baseline 
SST = sum((baseline-pisaTest$readingScore)^2)
SST
R2=1-(SSE/SST)
R2
